/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "apiText": "Prowl API key",
    "done": "done",
    "download": "download",
    "explanation": "You can enter up to 5 API keys by seperating them with commas.",
    "fail": "message failed\nplease try again",
    "iaian7com": "For more information, please visit iaian7.com/dashboard/prowler",
    "locationText": "System location of prowl.pl",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "push": "push",
    "skip": "skip version",
    "success": "message was\nsent successfully",
    "wrong": "invalid API key\nor other error"
};
