/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "apiText": { "creationFunction": "CreateText", "text": "apiText" },
    "doneSave": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showFront", "rightImageWidth": 5, "text": "done" },
    "download": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "versionDownload", "rightImageWidth": 5, "text": "download" },
    "explanation": { "creationFunction": "CreateText", "text": "explanation" },
    "failButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "failText": { "creationFunction": "CreateText", "text": "fail" },
    "group": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "group" },
    "iaian7com": { "creationFunction": "CreateText", "text": "iaian7com" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "new": { "creationFunction": "CreateText", "text": "new" },
    "newVersion": { "creationFunction": "CreateText", "text": "newVersion" },
    "priority": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "name": "priority", "options": [["very low", "-2"], ["moderate", "-1"], ["normal", "0", true], ["high", "1"], ["emergency", "2"]], "rightImageWidth": 16 },
    "push": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "push", "rightImageWidth": 5, "text": "push" },
    "skip": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "skip" },
    "stack": { "creationFunction": "CreateStackLayout", "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }] },
    "successButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "successText": { "creationFunction": "CreateText", "text": "success" },
    "text": { "creationFunction": "CreateText", "text": "©2009 John Einselen / Vectorform LLC" },
    "wrongButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done" },
    "wrongText": { "creationFunction": "CreateText", "text": "wrong" }
};
